services:
  - type: web
    name: ytdl-downloader
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: YTDL_NO_UPDATE
        value: true
